import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "./components/navbar";
import Slide from "./components/slide";
import Tab from "react-bootstrap/Tab";
import Tabs from "react-bootstrap/Tabs";
import Cabelo from "./components/cabelo";
import Unhas from "./components/unhas";
import Depilacao from "./components/Depilacao";
import Footer from "./components/footer";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Espaço - vip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/2.jpg" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css"
          integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor"
          crossOrigin=""
        />
      </Head>
      <Navbar />
      <div className={styles.banner} id="inicio">
        <Image src="/2.jpg" layout="responsive" width={1000} height={600} />
      </div>
      <main className={styles.main}>
        <div className={styles.content}>
          <h1 id="Servicos"> Serviços</h1>
          <Tabs
            defaultActiveKey="profile"
            id="uncontrolled-tab-example"
            className="mb-3"
          >
            <Tab eventKey="profile" title="Depilação a laser">
              <Depilacao />
            </Tab>
            <Tab eventKey="profile2" title="Manicure e pedicure">
              <Unhas />
            </Tab>
            <Tab eventKey="profile3" title="Cabelereiro">
              <Cabelo />
            </Tab>
            <Tab eventKey="profile4" title="Designer de sombrancelhas">
              <Depilacao />
            </Tab>
          </Tabs>
        </div>

        <div className={styles.about} id="Sobre">
          <div className={styles.aboutCard}>
            <h2>Sobre</h2>
            <p>
              Occaecat sint anim eiusmod laboris enim labore proident cupidatat
              enim velit duis irure. Ipsum ut cupidatat duis exercitation est.
              Sit qui magna non eu sunt duis est duis enim excepteur amet.
              Officia et aliquip mollit id veniam cillum sint. Consequat qui
              Lorem sunt eiusmod nisi. Velit do sint consequat quis
              reprehenderit eiusmod velit deserunt aliqua.
            </p>
          </div>
        </div>
        <div className={styles.typ}>
          <div className={styles.rota}>
            <div className={styles.rotaCard}>
              <h2>Como chegar?</h2>

              <Link href="https://www.google.com.br/maps/place/R.+Maria+Gorete,+04+-+Cidade+Nova,+Iguaba+Grande+-+RJ,+28960-000/@-22.835481,-42.2103182,17z/data=!3m1!4b1!4m5!3m4!1s0x971291b4b47029:0x186a36f0d2f89d29!8m2!3d-22.835486!4d-42.2081242">
                <p>
                  RUA MARIA GORETE 04 <strong> CIDADE NOVA</strong> , IGUABA
                  GRANDE.
                  <img src="/maps_logo.png" className={styles.GitImg} />
                </p>
              </Link>
            </div>
          </div>
        </div>
        <div className={styles.Social}>
          <div className={styles.SocialCard}>
            <h2>Já segue a gente?</h2>
            <Link href="https://www.google.com.br/maps/place/R.+Maria+Gorete,+04+-+Cidade+Nova,+Iguaba+Grande+-+RJ,+28960-000/@-22.835481,-42.2103182,17z/data=!3m1!4b1!4m5!3m4!1s0x971291b4b47029:0x186a36f0d2f89d29!8m2!3d-22.835486!4d-42.2081242">
              <p>
                Seguir -
                <img src="/instagram_ready.png" className={styles.instaImg} />
              </p>
            </Link>
            <h2>Deseja marcar um horário?</h2>
            <Link href="https://alvo.chat/7M5">
              <p>
                acesse -
                <img src="/whattsapp_logo.png" className={styles.GitImg} />
              </p>
            </Link>
          </div>
        </div>
      </main>
      <Slide />
      <Footer />
    </div>
  );
}
